//testnet
export const auctionAddressT = "TJd9zyMr2CaQsMtDbbQMqVrnnPHxssHDFG";

export const auctionAbiT = [
    {
      inputs: [
        { name: "_nftContract", type: "address" },
        { name: "_treasury", type: "address" },
      ],
      stateMutability: "Nonpayable",
      type: "Constructor",
    },
    {
      inputs: [{ indexed: true, name: "auctionId", type: "uint256" }],
      name: "AuctionCancelled",
      type: "Event",
    },
    {
      inputs: [
        { indexed: true, name: "auctionId", type: "uint256" },
        { name: "nftContract", type: "address" },
        { indexed: true, name: "tokenId", type: "uint256" },
        { name: "seller", type: "address" },
        { name: "duration", type: "uint256" },
        { name: "startTime", type: "uint256" },
        { name: "isActive", type: "bool" },
        { name: "Reserveprice", type: "uint256" },
        { name: "sold", type: "bool" },
      ],
      name: "AuctionCreated",
      type: "Event",
    },
    {
      inputs: [{ indexed: true, name: "auctionId", type: "uint256" }],
      name: "AuctionEnded",
      type: "Event",
    },
    {
      inputs: [
        { indexed: true, name: "auctionId", type: "uint256" },
        { name: "bidder", type: "address" },
        { name: "amount", type: "uint256" },
      ],
      name: "BidPlaced",
      type: "Event",
    },
    {
      inputs: [{ indexed: true, name: "auctionId", type: "uint256" }],
      name: "NftClaimed",
      type: "Event",
    },
    {
      inputs: [
        { indexed: true, name: "previousOwner", type: "address" },
        { indexed: true, name: "newOwner", type: "address" },
      ],
      name: "OwnershipTransferred",
      type: "Event",
    },
    {
      outputs: [{ name: "_value", type: "uint256" }],
      name: "_auctionIds",
      stateMutability: "View",
      type: "Function",
    },
    {
      inputs: [{ name: "auctionId", type: "uint256" }],
      name: "cancelAuction",
      stateMutability: "Nonpayable",
      type: "Function",
    },
    {
      inputs: [{ name: "auctionId", type: "uint256" }],
      name: "claimNft",
      stateMutability: "Nonpayable",
      type: "Function",
    },
    {
      inputs: [
        { name: "nftContract", type: "address" },
        { name: "tokenId", type: "uint256" },
        { name: "price", type: "uint256" },
        { name: "duration", type: "uint256" },
      ],
      name: "createAuction",
      stateMutability: "Nonpayable",
      type: "Function",
    },
    {
      inputs: [{ name: "auctionId", type: "uint256" }],
      name: "endAuction",
      stateMutability: "Nonpayable",
      type: "Function",
    },
    {
      outputs: [{ type: "tuple[]" }],
      inputs: [{ name: "user", type: "address" }],
      name: "fetchMyNFTs",
      stateMutability: "View",
      type: "Function",
    },
    {
      outputs: [{ type: "tuple[]" }],
      name: "fetchSoldAuctions",
      stateMutability: "View",
      type: "Function",
    },
    {
      outputs: [{ type: "tuple[]" }],
      name: "fetchUnsoldAuctions",
      stateMutability: "View",
      type: "Function",
    },
    {
      outputs: [{ type: "tuple[]" }],
      inputs: [{ name: "user", type: "address" }],
      name: "fetchauctionsBid",
      stateMutability: "View",
      type: "Function",
    },
    {
      outputs: [{ type: "uint256" }],
      inputs: [{ name: "auctionId", type: "uint256" }],
      name: "getReservePrice",
      stateMutability: "View",
      type: "Function",
    },
    {
      outputs: [
        { name: "auctionId", type: "uint256" },
        { name: "nftContract", type: "address" },
        { name: "tokenId", type: "uint256" },
        { name: "amount", type: "uint256" },
        { name: "duration", type: "uint256" },
        { name: "reservePrice", type: "uint256" },
        { name: "seller", type: "address" },
        { name: "bidder", type: "address" },
        { name: "minter", type: "address" },
        { name: "royalty", type: "uint256" },
        { name: "isActive", type: "bool" },
        { name: "sold", type: "bool" },
        { name: "startTime", type: "uint256" },
      ],
      inputs: [{ type: "uint256" }],
      name: "idToAuction",
      stateMutability: "View",
      type: "Function",
    },
    {
      outputs: [{ name: "bidder", type: "address" }],
      inputs: [{ name: "auctionId", type: "uint256" }],
      name: "isHighestBidder",
      stateMutability: "View",
      type: "Function",
    },
    {
      outputs: [{ type: "bytes4" }],
      inputs: [
        { type: "address" },
        { type: "address" },
        { type: "uint256" },
        { type: "bytes" },
      ],
      name: "onERC721Received",
      stateMutability: "Nonpayable",
      type: "Function",
    },
    {
      outputs: [{ type: "address" }],
      name: "owner",
      stateMutability: "View",
      type: "Function",
    },
    {
      inputs: [{ name: "auctionId", type: "uint256" }],
      name: "placeBid",
      stateMutability: "Payable",
      type: "Function",
    },
    {
      name: "renounceOwnership",
      stateMutability: "Nonpayable",
      type: "Function",
    },
    {
      inputs: [{ name: "_treasury", type: "address" }],
      name: "setTreasury",
      stateMutability: "Nonpayable",
      type: "Function",
    },
    {
      inputs: [{ name: "royalty", type: "uint256" }],
      name: "setTreasuryRoyalty",
      stateMutability: "Nonpayable",
      type: "Function",
    },
    {
      outputs: [
        { name: "timeEnd", type: "uint256" },
        { name: "timeleft", type: "uint256" },
      ],
      inputs: [{ name: "auctionId", type: "uint256" }],
      name: "timeLeftForAuctionToEnd",
      stateMutability: "View",
      type: "Function",
    },
    {
      inputs: [{ name: "newOwner", type: "address" }],
      name: "transferOwnership",
      stateMutability: "Nonpayable",
      type: "Function",
    },
    {
      outputs: [{ type: "address" }],
      name: "unicusNft",
      stateMutability: "View",
      type: "Function",
    },
  ];