//testnet
export const marketPlaceAddressT = "TWjJF6eMgujSJ5c6ofqwT8RGvQKgGbAdA1";

export const marketPlaceAbiT = [
    {
      inputs: [
        { name: "_nftContract", type: "address" },
        { name: "_treasury", type: "address" },
      ],
      stateMutability: "Nonpayable",
      type: "Constructor",
    },
    {
      inputs: [
        { indexed: true, name: "itemId", type: "uint256" },
        { indexed: true, name: "nftContract", type: "address" },
        { indexed: true, name: "tokenId", type: "uint256" },
        { name: "buyer", type: "address" },
        { name: "price", type: "uint256" },
        { name: "sold", type: "bool" },
        { name: "isActive", type: "bool" },
      ],
      name: "ItemBought",
      type: "Event",
    },
    {
      inputs: [
        { indexed: true, name: "previousOwner", type: "address" },
        { indexed: true, name: "newOwner", type: "address" },
      ],
      name: "OwnershipTransferred",
      type: "Event",
    },
    {
      inputs: [
        { indexed: true, name: "itemId", type: "uint256" },
        { indexed: true, name: "nftContract", type: "address" },
        { indexed: true, name: "tokenId", type: "uint256" },
        { name: "seller", type: "address" },
        { name: "owner", type: "address" },
        { name: "minter", type: "address" },
        { name: "royalty", type: "uint256" },
        { name: "price", type: "uint256" },
        { name: "sold", type: "bool" },
        { name: "isActive", type: "bool" },
      ],
      name: "saleCreated",
      type: "Event",
    },
    { stateMutability: "Payable", type: "Fallback" },
    {
      inputs: [{ name: "itemId", type: "uint256" }],
      name: "EndSale",
      stateMutability: "Nonpayable",
      type: "Function",
    },
    {
      inputs: [{ name: "itemId", type: "uint256" }],
      name: "buyItem",
      stateMutability: "Payable",
      type: "Function",
    },
    {
      inputs: [
        { name: "nftContract", type: "address" },
        { name: "tokenId", type: "uint256" },
        { name: "price", type: "uint256" },
      ],
      name: "createSale",
      stateMutability: "Nonpayable",
      type: "Function",
    },
    {
      outputs: [{ type: "tuple[]" }],
      name: "fetchItemsCreated",
      stateMutability: "View",
      type: "Function",
    },
    {
      outputs: [{ type: "tuple[]" }],
      name: "fetchMarketItems",
      stateMutability: "View",
      type: "Function",
    },
    {
      outputs: [{ type: "tuple[]" }],
      name: "fetchMyNFTs",
      stateMutability: "View",
      type: "Function",
    },
    {
      outputs: [{ type: "uint256" }],
      inputs: [{ name: "itemid", type: "uint256" }],
      name: "getPrice",
      stateMutability: "View",
      type: "Function",
    },
    {
      outputs: [
        { name: "itemId", type: "uint256" },
        { name: "nftContract", type: "address" },
        { name: "tokenId", type: "uint256" },
        { name: "seller", type: "address" },
        { name: "owner", type: "address" },
        { name: "minter", type: "address" },
        { name: "royalty", type: "uint256" },
        { name: "price", type: "uint256" },
        { name: "sold", type: "bool" },
        { name: "isActive", type: "bool" },
      ],
      inputs: [{ type: "uint256" }],
      name: "idToMarketItem",
      stateMutability: "View",
      type: "Function",
    },
    {
      outputs: [{ type: "bytes4" }],
      inputs: [
        { type: "address" },
        { type: "address" },
        { type: "uint256" },
        { type: "bytes" },
      ],
      name: "onERC721Received",
      stateMutability: "Nonpayable",
      type: "Function",
    },
    {
      outputs: [{ type: "address" }],
      name: "owner",
      stateMutability: "View",
      type: "Function",
    },
    {
      name: "renounceOwnership",
      stateMutability: "Nonpayable",
      type: "Function",
    },
    {
      outputs: [{ type: "uint256" }],
      inputs: [{ name: "item", type: "uint256" }],
      name: "royaltyForItem",
      stateMutability: "View",
      type: "Function",
    },
    {
      inputs: [{ name: "_treasury", type: "address" }],
      name: "setTreasury",
      stateMutability: "Nonpayable",
      type: "Function",
    },
    {
      inputs: [{ name: "royalty", type: "uint256" }],
      name: "setTreasuryRoyalty",
      stateMutability: "Nonpayable",
      type: "Function",
    },
    {
      inputs: [{ name: "newOwner", type: "address" }],
      name: "transferOwnership",
      stateMutability: "Nonpayable",
      type: "Function",
    },
    {
      outputs: [{ type: "uint256" }],
      name: "treasuryRoyalty",
      stateMutability: "View",
      type: "Function",
    },
    {
      outputs: [{ type: "address" }],
      name: "unicusNft",
      stateMutability: "View",
      type: "Function",
    },
    { stateMutability: "Payable", type: "Receive" },
  ];