export const CONNECT_WALLET: string = 'CONNECT_WALLET'
export const PROFILE_REQUEST: string = 'PROFILE_REQUEST'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const ACCESS_TOKEN = 'ACCESS_TOKEN'
export const REGISTER_WALLET = 'REGISTER_WALLET'
export const USER_INFO = 'USER_INFO'
export const PROFILE_FAIL: string = 'PROFILE_FAIL'
export const USER_ADDRESS: string = 'USER_ADDRESS'

// Market place
export const GET_ALL_NFTS_REQUEST: string = 'GET_ALL_NFTS_REQUEST'
export const GET_ALL_NFTS_FAIL: string = 'GET_ALL_NFTS_FAIL'
export const GET_MARKET_NFTS_SUCCESS: string = 'GET_MARKET_NFTS_SUCCESS'
export const GET_ALL_NFTS_SUCCESS: string = 'GET_ALL_NFTS_SUCCESS'
export const GET_PORTFOLIO_NFTS_SUCCESS: string = 'GET_PORTFOLIO_NFTS_SUCCESS'
export const GET_AUCTION_NFTS_SUCCESS: string = 'GET_AUCTION_NFTS_SUCCESS'
export const MARKET_NFTS_LOADED: string = 'MARKET_NFTS_LOADED'
export const PORTFOLIO_NFTS_LOADED: string = 'PORTFOLIO_NFTS_LOADED'
export const ALL_NFTS_LOADED: string = 'ALL_NFTS_LOADED'
export const AUCTION_NFTS_LOADED: string = 'AUCTION_NFTS_LOADED'
export const GET_TYPE_OF_NFT: string = 'GET_TYPE_OF_NFT'
export const GET_COUNTDOWN: string = 'GET_COUNTDOWN'
export const GET_NETWORK_ID: string = 'GET_NETWORK_ID'
export const GET_ASSET_DATA: string = 'GET_ASSET_DATA'
export const PROVIDER: string = 'PROVIDER'
